### PR TITLE
Merge

### PR DESCRIPTION
**Pull request by nihilus**

### CODE REVIEW

**Comment by hlide** [comment]
Are you sure that is what you wanted? you probably wanted in the opposite direction.

**Comment by nihilus** [comment]
Already did so... ;-)

**Comment by nihilus** [comment]
I was thinking maybe you wanted an update :-)

**Comment by hlide** [comment]
for the moment, I don't need since I'm focusing upon Allegrex. But thanks anyway.

**Comment by nihilus** [comment]
@hlide Actually you do want to look at the ELFParser if you'vent fixed it.

**Pull request closed without merging**
